import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-950`}>
        <header className="flex h-32 items-center bg-gradient-to-br from-gray-900 to-blue-900 pl-20 text-white">
          <h1 className="text-3xl font-semibold tracking-widest">
            Type-ahead with Next.js <br /> and Elasticsearch
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
